### PR TITLE
.NET 7 update

### PR DESCRIPTION
**Pull request by dradovic**
according to 884f0e534cd938f7ee10ff16dae1f6562e4ba0e9

### CODE REVIEW

**Comment by dradovic** [comment]
Fixes #26

**Review by raziems — APPROVED** [review]
Approved.

**Comment by EduardSergeev** [comment]
Could someone please merge this PR?
It is a great tool for certififcate management but being stuck with .NET 6 is a major limitation these days.

Or is there some other way to use `dotnet-certificate` with only .NET 7 SDK installed on a target machine? We use it in our `Dockerfile` and would prefer to use it in `FROM mcr.microsoft.com/dotnet/sdk:7.0 AS build-env` image...

**Comment by mahdi-openup** [comment]
needed here as well

**Comment by Sumit10612** [comment]
any plans for merging this PR?

**Comment by dradovic** [comment]
So while waiting to see if this repo still has active maintainers, note that you could use my unofficial release which I had to publish due to the lack of a response here: [https://www.nuget.org/packages/dotnet-certificate-tool-net7](https://www.nuget.org/packages/dotnet-certificate-tool-net7)

**Comment by Sumit10612** [comment]
yeah, I have done the same.

**Comment by decarufe** [comment]
See: [Seeking New Maintainers for dotnet-certificat-tool](https://github.com/gsoft-inc/dotnet-certificate-tool/issues/34)

**Comment by stylianosnicoletti** [comment]
.net 8 and .net 7 support completed and pushed on Nuget.org

**Comment by stylianosnicoletti** [comment]
.net 8 and .net 7 support completed and pushed on Nuget.org

**Pull request closed without merging**
